config/routes.rb
Rails.application.routes.draw do

    root 'home#index'

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations"
    }

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end


    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      resources :portfolios
      resources :categories
      resources :blogs
      resources :admins
      # Sale
      resources :category_portfolios
      resources :products
      resources :product_types
      resources :galleries
      resources :orders
      resources :line_items
      resources :settings, only: [:new, :create, :edit, :update]
      resources :users
      resources :settings, only: [:new, :create, :edit, :update]
      resources :incomes
      resources :expenses
      resources :accounts
      resources :income_and_expense_dashboards
    end

    resources :blogs

    resources :wishlists
    resources :products do
      resources :reviews
    end

    resources :orders
    resources :product_types, only: [:index, :show]
    get 'profiles' => "orders#profile", :as => "profiles"
    get 'carts/:id' => 'carts#show', as: "cart"
    delete 'carts/:id' => 'carts#destroy'

    post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
    post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
    post 'line_items/:id/s_size'=> 'line_items#s_size', as: 's_size'
    post 'line_items/:id/m_size'=> 'line_items#m_size', as: 'm_size'
    post 'line_items/:id/l_size'=> 'line_items#l_size', as: 'l_size'
    post 'line_items/:id/xl_size'=> 'line_items#xl_size', as: 'xl_size'
    post 'line_items' => 'line_items#create'
    get 'line_items/:id' => 'line_items#shiow', as: "line_item"
    delete 'line_items/:id' => 'line_items#destroy'

    post 'wishlist_line_items/:id/add' => 'wishlist_line_items#add_quantity', as: 'wishlist_line_item_add'
    post 'wishlist_line_items/:id/reduce' => 'wishlist_line_items#reduce_quantity', as: 'wishlist_line_item_reduce'
    post 'wishlist_line_items' => 'wishlist_line_items#create'
    get 'wishlist_line_items/:id' => 'wishlist_line_items#shiow', as: "wishlist_line_item"
    delete 'wishlist_line_items/:id' => 'wishlist_line_items#destroy'

    get 'users' => 'users#index', :as => "users"
    post 'users' => "users#create"
    get 'signup' => "users#new", :as => "new_user"
    get "users/:id/edit" => "users#edit", :as => "edit_user"
    get "users/:id" => "users#show", :as => "user"
    patch "users/:id" => "users#update"
    put "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"

    get 'under_constructions' => "static_pages#under_construction", as: "under_construction"
    get 'profile' => "orders#profile", as: "profile"
    resources :product_types
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout "application"
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
  before_action :configure_permitted_parameters, if: :devise_controller?

  before_action :set_locale
  before_action :set_cart
  before_action :set_wishlist
  before_action :search_product
  # respond_to :html, :xml, :json, :js

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone_number,:country_code,:role,:email,:password])
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone_number, :role, :email,:password,:password_confirmation,:current_password])
  end

  def after_sign_out_path_for(resource_or_scope)
    session[:login_url] || request.referer || root_path
  end

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  def store_current_location
    session['user_return_to'] = request.url
  end

  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      if admin_signed_in?
        admin_dashboard_path
      else
        root_path
      end
    else
      super
    end
  end

  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  def set_locale
    locale = I18n.available_locales.include?(params[:locale].to_sym) ? params[:locale] : I18n.locale if params[:locale].present?
    I18n.locale = locale || I18n.locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge(options)
  end
  private

    def set_cart
        if session[:cart_id]
            cart = Cart.find_by(id: session[:cart_id])
            if cart.present?
              @current_cart = cart
              if current_user
                cart.update(user_id: current_user.id)
              end
            else
              session[:cart_id] = nil
            end
          end

            if session[:cart_id].nil?
              if current_user
                @current_cart = Cart.create(:user_id => current_user.id)
                session[:cart_id] = @current_cart.id
              end
              @current_cart = Cart.create(:user_id => nil)
              session[:cart_id] = @current_cart.id
            end
       end

        def set_wishlist
          if session[:wishlist_id]
            wishlist = Wishlist.find_by(id: session[:wishlist_id])
            if wishlist.present?
              @current_wishlist = wishlist
              if current_user
                wishlist.update(user_id: current_user.id)
              end
            else
              session[:wishlist_id] = nil
            end
          end

          if session[:wishlist_id].nil?
            if current_user
              @current_wishlist = Wishlist.create(:user_id => current_user.id)
              session[:wishlist_id] = @current_wishlist.id
            end
            @current_wishlist = Wishlist.create(:user_id => nil)
            session[:wishlist_id] = @current_wishlist.id
          end
        end

        def search_product
          @cart = @current_cart
        end

        def time_ago(time)
          time
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def time_format(datetime)
    datetime.strftime('%H:%M') unless datetime.blank?
  end
end

app/views/applications/_nav.html.erb
<!-- HEADER -->
<header class="panhara_tm_header">
   <div class="panhara_tm_navigation_wrap">
      <div class="container">
         <div class="navigation_inner">
            <div class="logo">
               <a class="light_logo" href="/"><img src="/img/logo/logo.png" alt=""/></a>
            </div>
            <div class="nav_list_wrap">
               <div class="menu">
                  <ul class="anchor_nav">
                     <li>
                        <a href="#home">Home</a>
                     </li>
                     <li>
                        <a href="#about">About</a>
                     </li>
                     <li>
                        <a href="#services">Services</a>
                     </li>
                     <li>
                        <a href="#portfolio">Portfolio</a>
                     </li>
                     <li>
                        <a href="#news">News</a>
                     </li>
                     <li>
                        <%=link_to "Products", products_path%>
                     </li>
                     <li>
                        <a href="#contact">Contact</a>
                     </li>
                     <%if user_signed_in?%>
                     <li id="fat-menu" class="dropdown">
                        <a href="#" class="dropdown-toggle" id="drop3" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Profile
                        <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="drop3">
                           <li>
                              <%=link_to "Your Account", profile_path%>
                           </li>
                           <li role="separator" class="divider"></li>
                           <li>
                              <%=link_to "Logout", destroy_user_session_path, method: :delete%>
                           </li>
                        </ul>
                     </li>
                     <%else%>
                     <li id="fat-menu" class="dropdown">
                        <a href="#" class="dropdown-toggle" id="drop3" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                        Account
                        <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="drop3">
                           <li>
                              <%=link_to "Sign In", sign_in_path%>
                           </li>
                           <li>
                              <%=link_to "Sign Up", sign_up_path%>
                           </li>
                        </ul>
                     </li>
                     <%end%>
                  </ul>
               </div>
            </div>
            <div class="panhara_tm_trigger">
               <div class="hamburger hamburger--collapse-r">
                  <div class="hamburger-box">
                     <div class="hamburger-inner"></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="panhara_tm_mobile_menu_wrap">
      <div class="mob_menu">
         <ul class="anchor_nav">
            <li>
               <a href="#home">Home</a>
            </li>
            <li>
               <a href="#about">About</a>
            </li>
            <li>
               <a href="#services">Services</a>
            </li>
            <li>
               <a href="#portfolio">Portfolio</a>
            </li>
            <li>
               <a href="#news">News</a>
            </li>
            <li>
               <%=link_to "Products", products_path%>
            </li>
            <li>
               <a href="#contact">Contact</a>
            </li>
            <%if user_signed_in?%>
            <li id="fat-menu" class="dropdown">
               <a href="#" class="dropdown-toggle" id="drop3" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
               Profile
               <span class="caret"></span>
               </a>
               <ul class="dropdown-menu" aria-labelledby="drop3">
                  <li>
                     <%=link_to "Your Account", profile_path%>
                  </li>
                  <li role="separator" class="divider"></li>
                  <li>
                     <%=link_to "Logout", destroy_user_session_path, method: :delete%>
                  </li>
               </ul>
            </li>
            <%else%>
            <li id="fat-menu" class="dropdown">
               <a href="#" class="dropdown-toggle" id="drop3" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
               Account
               <span class="caret"></span>
               </a>
               <ul class="dropdown-menu" aria-labelledby="drop3">
                  <li>
                     <%=link_to "Sign In", sign_in_path%>
                  </li>
                  <li>
                     <%=link_to "Sign Up", sign_up_path%>
                  </li>
               </ul>
            </li>
            <%end%>
         </ul>
      </div>
   </div>
</header>
<!-- /HEADER -->

app/views/applications/_sidebar.html.erb
<div class="col-lg-4">
   <ul class="sidebar-menu">
      <li>
         <span class="nav-section-title"></span>
      </li>
      <li>
         <%=link_to admin_dashboard_path do%>
         <span class="fa fa-dashboard"></span>Dashboard
         <%end%>
      </li>
      <li>
         <%=link_to admin_users_path do%>
         <span class="fa fa-users"></span>Customer
         <%end%>
      </li>
      <li>
         <%=link_to admin_admins_path do%>
         <span class="fa fa-users"></span>Administrator
         <%end%>
      </li>
      <li class="have-children">
         <a href="#">
         <span class="fa fa-file"></span>Content
         </a>
         <ul>
            <li>
               <%=link_to "Category", admin_categories_path%>
            </li>
            <li>
               <%=link_to "Blog", admin_blogs_path%>
            </li>
         </ul>
      </li>
      <li class="have-children">
         <a href="#">
         <span class="fa fa-user-circle-o"></span>Portfolio
         </a>
         <ul>
            <li>
               <%=link_to "Category", admin_category_portfolios_path%>
            </li>
            <li>
               <%=link_to "Portfolio", admin_portfolios_path%>
            </li>
         </ul>
      </li>
      <li class="have-children">
         <a href="#">
         <span class="fa fa-product-hunt"></span>Inventory
         </a>
         <ul>
            <li>
               <%=link_to "Types", admin_product_types_path%>
            </li>
            <li>
               <%=link_to "Products", admin_products_path%>
            </li>
         </ul>
      </li>
      <li>
         <%=link_to admin_orders_path do%>
         <span class="fa fa-cart-arrow-down"></span>Order
         <%end%>
      </li>
      <li>
         <%=link_to admin_line_items_path do%>
         <span class="fa fa-binoculars"></span>Order Details
         <%end%>
      </li>
      <li>
         <%=link_to edit_admin_setting_path(2) do%>
         <span class="fa fa-gear"></span>Settings
         <%end%>
      </li>
      <li>
         <a href="#">
         <span class="fa fa-bug"></span>Configuration
         </a>
      </li>
   </ul>
</div>