config/routes.rb
Rails.application.routes.draw do

    root 'home#index'

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations"
    }

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end


    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      resources :portfolios
      resources :categories
      resources :blogs
      resources :admins
      # Sale
      resources :category_portfolios
      resources :products
      resources :product_types
      resources :galleries
      resources :orders
      resources :line_items
      resources :settings, only: [:new, :create, :edit, :update]
      resources :users
      resources :settings, only: [:new, :create, :edit, :update]
      resources :incomes
      resources :expenses
      resources :accounts
      resources :income_and_expense_dashboards
    end

    resources :blogs

    resources :wishlists
    resources :products do
      resources :reviews
    end

    resources :orders
    resources :product_types, only: [:index, :show]
    get 'profiles' => "orders#profile", :as => "profiles"
    get 'carts/:id' => 'carts#show', as: "cart"
    delete 'carts/:id' => 'carts#destroy'

    post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
    post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
    post 'line_items/:id/s_size'=> 'line_items#s_size', as: 's_size'
    post 'line_items/:id/m_size'=> 'line_items#m_size', as: 'm_size'
    post 'line_items/:id/l_size'=> 'line_items#l_size', as: 'l_size'
    post 'line_items/:id/xl_size'=> 'line_items#xl_size', as: 'xl_size'
    post 'line_items' => 'line_items#create'
    get 'line_items/:id' => 'line_items#shiow', as: "line_item"
    delete 'line_items/:id' => 'line_items#destroy'

    post 'wishlist_line_items/:id/add' => 'wishlist_line_items#add_quantity', as: 'wishlist_line_item_add'
    post 'wishlist_line_items/:id/reduce' => 'wishlist_line_items#reduce_quantity', as: 'wishlist_line_item_reduce'
    post 'wishlist_line_items' => 'wishlist_line_items#create'
    get 'wishlist_line_items/:id' => 'wishlist_line_items#shiow', as: "wishlist_line_item"
    delete 'wishlist_line_items/:id' => 'wishlist_line_items#destroy'

    get 'users' => 'users#index', :as => "users"
    post 'users' => "users#create"
    get 'signup' => "users#new", :as => "new_user"
    get "users/:id/edit" => "users#edit", :as => "edit_user"
    get "users/:id" => "users#show", :as => "user"
    patch "users/:id" => "users#update"
    put "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"

    get 'under_constructions' => "static_pages#under_construction", as: "under_construction"
    get 'profile' => "orders#profile", as: "profile"
    resources :product_types
end

app/views/cart_shared/_cart.html.erb
<div id="out_of_stock_error" style="display: none;"></div>
<style media="screen">
   .panhara_tm_header {
   display: none;
   }
</style>
<%=render "products/product_nav"%>
<div class="panhara_tm_content">
   <div class="panhara_tm_section" style="margin-top: 150px;">
      <div class="container-fluid">
         <div class="wrapper">
            <div class="cart-main-area pt-90 pb-100">
               <h3 class="cart-page-title">Your cart items</h3>
               <div class="row">
                  <div class="col-lg-9 col-md-12 col-sm-12 col-12">
                     <div class="table-content table-responsive cart-table-content">
                        <table>
                           <thead>
                              <tr>
                                 <th>Image</th>
                                 <th>Product Name</th>
                                 <th>Until Price</th>
                                 <th>Qty</th>
                                 <th>Size</th>
                                 <th>action</th>
                              </tr>
                           </thead>
                           <tbody>
                              <%@cart.line_items.each do |line_item|%>
                              <tr>
                                 <td class="product-thumbnail">
                                    <%line_item.product.assets.limit(1).each do |asset|%>
                                    <a href="#"><img src="<%=asset.image%>" alt="" style="width: 60%;"></a>
                                    <%end%>
                                 </td>
                                 <td class="product-name">
                                    <a href="#"><%=line_item.product.product_name.capitalize%></a>
                                 </td>
                                 <td class="product-price-cart">
                                    <span class="amount"><%=number_to_currency(line_item.product.product_price)%></span>
                                 </td>
                                 <td class="product-quantity">
                                    <%=link_to line_item_reduce_path(:id => line_item) , method: :post , style: "margin-top:15px; color: #fd4d4d;",class: "reduce-qty",remote: true do %>
                                    <i class="fa fa-minus"></i>
                                    <% end %>
                                    <span class="qty" id="qty_<%=line_item.id%>"><%=line_item.quantity%></span>
                                    <%=link_to line_item_add_path(:id => line_item) , method: :post , style: "margin-top:15px; color: #fd4d4d;",class: "increase-qty",remote: true do %>
                                    <i class="fa fa-plus"></i>
                                    <% end %>
                                 </td>
                                 <td style="width: 100%;padding-top: 0px;">
                                    <%=button_to s_size_path(:id => line_item, shirt_size: 'S') , method: :post , style: "margin-top:15px; color: #fd4d4d;",id: "selected_#{line_item.id}_s",class:"selected", remote: true do %>
                                    S
                                    <% end %>
                                    <%=button_to m_size_path(:id => line_item, shirt_size: 'M') , method: :post , style: "margin-top:15px; color: #fd4d4d;",id: "selected_#{line_item.id}_m",class:"selected", remote: true do %>
                                    M
                                    <% end %>
                                    <%=button_to l_size_path(:id => line_item, shirt_size: 'L') , method: :post , style: "margin-top:15px; color: #fd4d4d;",id: "selected_#{line_item.id}_l",class:"selected", remote: true do %>
                                    L
                                    <% end %>
                                    <%=button_to xl_size_path(:id => line_item, shirt_size: 'XL') , method: :post , style: "margin-top:15px; color: #fd4d4d;",id: "selected_#{line_item.id}_xl",class:"selected", remote: true do %>
                                    XL
                                    <% end %>
                                 </td>
                                 <td class="product-remove">
                                    <%=link_to line_item_path(@current_cart.line_items.find_by(product_id: line_item.product.id)) ,method: :delete do %>
                                    <i class="fa fa-times" style="color: #fd4d4d;"></i>
                                    <% end %>
                                 </td>
                              </tr>
                              <%end%>
                           </tbody>
                        </table>
                     </div>
                     <div class="row">
                        <div class="col-lg-12">
                           <div class="cart-shiping-update-wrapper">
                              <div class="cart-shiping-update">
                                 <%=link_to "Continue Shopping", products_path%>
                              </div>
                           </div>
                        </div>
                     </div>
                  </div>
                  <div class="col-lg-3 col-md-12">
                     <div class="grand-totall">
                        <div class="title-wrap">
                           <h4 class="cart-bottom-title section-bg-gary-cart">Cart Total</h4>
                        </div>
                        <h5>Total products
                           <span id="sub_total"><%=number_to_currency(@cart.sub_total)%></span>
                        </h5>
                        <h4 class="grand-totall-title" style="color: #fd4d4d;">Grand Total
                           <span id="grand_sub_total"><%=number_to_currency(@cart.sub_total)%></span>
                        </h4>
                        <%= link_to "Checkout", new_order_path , method: :get, style: "background: #fd4d4d;"%>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- /ABOUT -->
   <%=render "shared/footer"%>
</div>
<!-- /CONTENT -->
<div id="minus_one" style="display: none;"></div>

app/views/cart_shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/cart_shared/_wishlist.html.erb
<style media="screen">
   .panhara_tm_header {
   display: none;
   }
</style>
<%=render "products/product_nav"%>
<div class="panhara_tm_content">
   <div class="panhara_tm_section">
      <div class="container-fluid">
         <div class="panhara_tm_about_wrap">
            <div class="wrapper">
               <div class="cart-main-area pt-90 pb-100">
                  <h3 class="cart-page-title">Your Wishlist Items</h3>
                  <div class="row">
                     <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                        <form action="#">
                           <div class="table-content table-responsive cart-table-content">
                              <table>
                                 <thead>
                                    <tr>
                                       <th>Image</th>
                                       <th>Product Name</th>
                                       <th>Until Price</th>
                                       <th>Add To Cart</th>
                                    </tr>
                                 </thead>
                                 <tbody>
                                    <%@wishlist.wishlist_line_items.each do |wishlist|%>
                                    <tr>
                                       <td class="product-thumbnail">
                                          <%wishlist.product.assets.limit(1).each do |product|%>
                                          <a href="#">
                                          <img src="<%=product.image%>" alt="" style="width: 60%;">
                                          </a>
                                          <%end%>
                                       </td>
                                       <td class="product-name">
                                          <a href="#"><%=wishlist.product.product_name.capitalize%></a>
                                       </td>
                                       <td class="product-price-cart">
                                          <span class="amount"><%=number_to_currency(wishlist.product.product_price)%></span>
                                       </td>
                                       <td class="product-wishlist-cart">
                                          <%=link_to product_path( wishlist.product.slug), class: "btn", style: "color: #fff;background: #fd4d4d;" do %>
                                          <i class="fa fa-shopping-cart"></i>
                                          Product Detail
                                          <% end %>
                                       </td>
                                    </tr>
                                    <%end%>
                                 </tbody>
                              </table>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- /ABOUT -->
   <%=render "shared/footer"%>
</div>
<!-- /CONTENT -->