config/routes.rb
Rails.application.routes.draw do

    root 'home#index'

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations"
    }

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end


    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      resources :portfolios
      resources :categories
      resources :blogs
      resources :admins
      # Sale
      resources :category_portfolios
      resources :products
      resources :product_types
      resources :galleries
      resources :orders
      resources :line_items
      resources :settings, only: [:new, :create, :edit, :update]
      resources :users
      resources :settings, only: [:new, :create, :edit, :update]
      resources :incomes
      resources :expenses
      resources :accounts
      resources :income_and_expense_dashboards
    end

    resources :blogs

    resources :wishlists
    resources :products do
      resources :reviews
    end

    resources :orders
    resources :product_types, only: [:index, :show]
    get 'profiles' => "orders#profile", :as => "profiles"
    get 'carts/:id' => 'carts#show', as: "cart"
    delete 'carts/:id' => 'carts#destroy'

    post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
    post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
    post 'line_items/:id/s_size'=> 'line_items#s_size', as: 's_size'
    post 'line_items/:id/m_size'=> 'line_items#m_size', as: 'm_size'
    post 'line_items/:id/l_size'=> 'line_items#l_size', as: 'l_size'
    post 'line_items/:id/xl_size'=> 'line_items#xl_size', as: 'xl_size'
    post 'line_items' => 'line_items#create'
    get 'line_items/:id' => 'line_items#shiow', as: "line_item"
    delete 'line_items/:id' => 'line_items#destroy'

    post 'wishlist_line_items/:id/add' => 'wishlist_line_items#add_quantity', as: 'wishlist_line_item_add'
    post 'wishlist_line_items/:id/reduce' => 'wishlist_line_items#reduce_quantity', as: 'wishlist_line_item_reduce'
    post 'wishlist_line_items' => 'wishlist_line_items#create'
    get 'wishlist_line_items/:id' => 'wishlist_line_items#shiow', as: "wishlist_line_item"
    delete 'wishlist_line_items/:id' => 'wishlist_line_items#destroy'

    get 'users' => 'users#index', :as => "users"
    post 'users' => "users#create"
    get 'signup' => "users#new", :as => "new_user"
    get "users/:id/edit" => "users#edit", :as => "edit_user"
    get "users/:id" => "users#show", :as => "user"
    patch "users/:id" => "users#update"
    put "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"

    get 'under_constructions' => "static_pages#under_construction", as: "under_construction"
    get 'profile' => "orders#profile", as: "profile"
    resources :product_types
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :line_items, dependent: :destroy
  belongs_to :user, optional: true
  belongs_to :admin, optional: true
  has_many :wishlist_line_items, dependent: :destroy
  validates :first_name, :last_name, :address_one, presence: true
  validates :first_name, :last_name, length: {maximum: 15}

  def sub_total
    sum = 0
    line_items.each do |line_item|
      sum += line_item.total_price
    end
    sum
  end


end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  before_action :admin_only?, except: [:index]

  def invoice
    @invoice = Order.find(params[:id])
  end

  def index
    @order = current_admin.orders.build
    @orders = Order.all.order(id: :desc)
  end

  def show
    @order = Order.find(params[:id])
  end

  def new

  end

  def create
    @order = current_admin.orders.build(order_params)
    if @order.save
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_orders_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or order Duplicated"
        format.html { redirect_to admin_orders_path }
        format.js { render template: "admin/categories/order_error.js.erb" }
      end
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      @order.line_items.each do |item|
        if @order.status == true
          item.product.update_columns(remaining_stock_quantity: item.product.remaining_stock_quantity - item.quantity)
        end
      end
      respond_to do |format|
        flash.now[:notice] = "Successful Updated"
        format.html { redirect_to admin_orders_path }
        format.js
      end
    else
      render :edit
    end
  end

  def destroy
    @order = Order.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_orders_url }
      format.js
    end
  end

  private
    def admin_only?
      unless  current_admin.admin?
        unless @user == current_admin
          redirect_to admin_dashboard_path, alert: "Access Denied"
        end
      end
    end

    def order_params
      params.required(:order).permit!
    end
end

app/controllers/orders_controller.rb
class OrdersController < FrontEndApplication
  before_action :authenticate_user!, only: [:index, :show, :new, :create, :profile]
  before_action :cart_is_empty, only: [:new, :create]
  before_action :isBlock?, only: [:create]
  def profile
    @orders = current_user.orders.all
    @categories = Category.all
  end

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new

    @order = Order.new
    @cart = @current_cart
  end

  def create
    @order = Order.new(order_params)
    @order.update(user_id: current_user.id)
    client = Slack::Web::Client.new
    client.auth_test
    if @order.save
      add_line_items_to_order
      reset_sessions_cart
      redirect_to profile_path
      flash[:notice] = "Thank for your order"
      client.chat_postMessage(
        channel: '#mybusiness',
        text: "http://www.panhara.work/admin/orders/#{@order.id}/edit",
        as_user: true
      )
    else
      flash[:alert] = "Please fill the bill infomation"
      render :new
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)
    redirect_to orders_path
  end

  def cart_is_empty
    return unless @current_cart.line_items.empty?
    flash[:alert] = "You cart is empty"
    redirect_to cart_path(@current_cart)
  end

  private
    def add_line_items_to_order
      @current_cart.line_items.each do |item|
        item.cart_id = nil
        item.order_id = @order.id
        item.save
        @order.line_items << item
      end
    end

    def reset_sessions_cart
      Cart.destroy(session[:cart_id])
      session[:cart_id] = nil
    end

    def isBlock?
      if current_user.isBlock == true
        redirect_to root_path, alert: "Your Account Was Blocked By Administrator Contact This Number 095477325"
      end
    end

    def order_params
      params.require(:order).permit(:user_id, :first_name, :last_name, :address_one, :address_two, :payment, :country, line_items_attributes:[:id, :product_id])
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/_edit.html.erb
<%=content_tag :div, class: "modal fade modal-slide-right", id: "edit_#{dom_id(@order, :modal)}" do%>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-md-12">
            <h5 class="m-b-0" id="edit_user">Edit Order</h5>
          </div>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%=simple_form_for([:admin, @order], remote: true) do |f|%>
        <div class="modal-body overflow-auto">
          <div class="form-row">
            <div class="col-md-12">
              <label class="cstm-switch">
                <%=f.check_box :status, class: "cstm-switch-input"%>
                <span class="cstm-switch-indicator "></span>
                <span class="cstm-switch-description"> Status </span>
              </label>
            </div>
          </div>
        </div>
        <div class="modal-footer justify-content-start">
          <%=f.submit "Update", class: "btn btn-primary"%>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <%end%>
    </div>
  </div>
<%end%>

app/views/admin/orders/_order.html.erb
<tr class="delete_order_<%=order.id%>">
  <td id="data_<%=order.id%>">
    <%=order.id%>
  </td>
  <td>
    <%=number_to_currency(order.sub_total)%>
  </td>
  <td>
    <%=order_status_converter(order.status, correct: "Delivered", incorrect: "In Progress")%>
  </td>
  <td>
    <%=time_ago(order.created_at)%>
  </td>
  <td>
    <%=time_ago(order.updated_at)%>
  </td>
  <td class="text-center">
    <%=form_for([:admin, order], remote: true) do |f|%>
      <%=link_to admin_order_path(order), remote: true,class: "btn btn-primary", "data-target" => "bd-example-modal-lg-panhara" do %>
        View
      <%end%>
      <%=link_to edit_admin_order_path(order),id: "link_#{order.id}",class: "btn btn-primary", remote: true do %>
        Edit
      <% end %>
    <%end%>
  </td>
</tr>

app/views/admin/orders/_show.html.erb
<%=content_tag :div, class: "modal fade bd-example-modal-lg", id: "detail_#{dom_id(@order, :modal)}" do%>
  <div class="modal-dialog modal-dialog-centered modal-lg modal-xxl" role="document">
     <div class="modal-content">
        <div class="modal-header">
           <h5 class="modal-title" id="myLargeModalLabel">Large Modal</h5>
           <button type="button" class="close" data-dismiss="modal" aria-label="Close">
           <span aria-hidden="true">&times;</span>
           </button>
        </div>
        <div class="modal-body">
           <div class="bg-dark m-b-30">
              <div class="container">
                 <div class="row p-b-60 p-t-60">
                    <div class="col-md-6 text-white p-b-30">
                       <div class="media">
                          <div class="avatar avatar mr-3">
                             <div class="avatar-title bg-success rounded-circle mdi mdi-receipt  "></div>
                          </div>
                          <div class="media-body">
                             <div class="opacity-75">To,</div>
                             <h4 class="m-b-0"><%=@order.address_one%>
                             </h4>
                             <p class="opacity-75">
                                Invoice ID <span>#00<%=@order.id%></span>
                                <br>
                                Invoice Date : <%=@order.created_at%>
                             </p>
                             <button class="btn btn-white-translucent" id="printDiv">
                             <i class="mdi
                                mdi-printer"></i>
                             Print</button>
                          </div>
                       </div>
                    </div>
                    <div class="col-md-5 text-center m-b-30 ml-auto">
                       <div class="rounded text-white bg-white-translucent">
                          <div class="p-all-15">
                             <div class="row">
                                <div class="col-md-6 my-2 m-md-0">
                                   <div class="text-overline    opacity-75">amount received</div>
                                   <h3 class="m-0 text-success"><%=number_to_currency(@order.sub_total)%></h3>
                                </div>
                                <div class="col-md-6 my-2 m-md-0">
                                   <div class="text-overline    opacity-75">amount pending</div>
                                   <h3 class="m-0 text-danger">$0</h3>
                                </div>
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
           <div class="pull-up">
              <div class="container" id="printableArea">
                 <div class="row">
                    <div class="col-md-12 m-b-40">
                       <div class="card">
                          <div class="card-body">
                             <div class="row">
                                <div class="col-md-6">
                                   <img src="assets/img/logos/nytimes.jpg" width="60" class="rounded-circle" alt="">
                                   <address class="m-t-10">
                                      To,<br>
                                      <span class="h4 font-primary">
                                      <%=@order.address_one%>
                                      </span>
                                   </address>
                                </div>
                                <div class="col-md-6 text-right my-auto">
                                   <h1 class="font-primary">INVOICE</h1>
                                   <div class="">Invoice Number: <span>#00<%=@order.id%></span></div>
                                   <div class="">Date: <%=@order.created_at%></div>
                                </div>
                             </div>
                             <div class="table-responsive ">
                                <table class="table m-t-50">
                                   <thead>
                                      <tr>
                                         <th class="">Products</th>
                                         <th class="text-center">QTY</th>
                                         <th class="text-center">Unit Price</th>
                                         <th class="text-right">Sub Total</th>
                                      </tr>
                                   </thead>
                                   <tbody>
                                      <%@order.line_items.each do |item|%>
                                      <tr>
                                         <td class="">
                                            <p class="text-black m-0"><%=item.product.product_name.capitalize%></p>
                                         </td>
                                         <td class="text-center"><%=item.quantity%></td>
                                         <td class="text-center"><%=number_to_currency(item.product.product_price)%></td>
                                         <td class="text-right"><%=number_to_currency(item.total_price)%></td>
                                      </tr>
                                      <%end%>
                                      <tr>
                                         <td colspan="3" class="text-right">
                                            Sub Total
                                         </td>
                                         <td colspan="2" class="text-right">
                                            <%=number_to_currency(@order.sub_total)%>
                                         </td>
                                      </tr>
                                      <tr>
                                         <td colspan="3" class="text-right">
                                            Discount
                                         </td>
                                         <td colspan="2" class="text-right">
                                            0.0
                                         </td>
                                      </tr>
                                      <tr class="">
                                         <td colspan="3" class="text-right">
                                            Taxes
                                         </td>
                                         <td colspan="2" class="text-right">
                                            $ 0.0
                                         </td>
                                      </tr>
                                      <tr class="bg-light">
                                         <td colspan="3" class="text-right">
                                            Total
                                         </td>
                                         <td colspan="2" class="text-right">
                                            <%=number_to_currency(@order.sub_total)%>
                                         </td>
                                      </tr>
                                   </tbody>
                                </table>
                             </div>
                             <div class="p-t-10 p-b-20">
                                <p class="text-muted ">
                                   Services will be invoiced in accordance with the Service Description. You must pay all undisputed invoices in full within 30 days of the invoice date, unless otherwise specified under the Special Terms and Conditions. All payments must reference the
                                   invoice number. Unless otherwise specified, all invoices shall be paid in the currency of the invoice
                                </p>
                                <hr>
                                <div class="text-center opacity-75">
                                   &copy; Panhara.work 2019
                                </div>
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
        </div>
        <div class="modal-footer">
           <button type="button" class="btn btn-secondary" data-dismiss="modal">
           Close
           </button>
           <button type="button" class="btn btn-primary">Save changes</button>
        </div>
     </div>
  </div>
<%end%>

app/views/admin/orders/destroy.js.erb
$('.delete_order_<%=@order.id%>').remove();

app/views/admin/orders/edit.js.erb
$('body').append('<%= j render partial: "admin/orders/edit"%>');
$('#edit_<%= dom_id @order, :modal%>').modal('toggle');
$('tr').find('td:nth-child(3)').each(function(){
  if ($(this).text().trim().replace(/ +/g, "") == "<%=order_status_converter(@order.status).gsub(/\s+/, '')%>") {
    $(this).parent().addClass("edit_row_<%=@order.id%>")
  }
});

app/views/admin/orders/index.html.erb
<div id="order-success"></div>
<%=render "admin/shared/aside"%>
<main class="admin-main">
   <!--site header begins-->
   <%=render "admin/shared/header"%>
   <!--site header ends -->
   <section class="admin-content">
      <div class="container">
      <!-- Content -->
      <div class="row">
         <div class="col-md-12">
            <div class="card m-b-30 m-t-30">
               <div class="card-header">
                  <h5 class="m-b-0">
                     <i class="mdi mdi-checkbox-intermediate"></i> Orders
                  </h5>
               </div>
               <div class="card-body">
                  <div class="table-responsive">
                     <table class="table table-hover align-td-middle">
                        <thead>
                           <tr>
                              <th>#</th>
                              <th>Total</th>
                              <th>Status</th>
                              <th>Created_At</th>
                              <th>Updated_At</th>
                              <th class="text-center">Action</th>
                           </tr>
                        </thead>
                        <tbody id="order-index">
                           <%if @orders.any?%>
                           <%= render @orders%>
                           <%end%>
                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Modal -->
   </section>
</main>

app/views/admin/orders/order_error.js.erb
$("#order-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/orders/order_success.js.erb
$("#admin-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/orders/show.js.erb
$('body').append('<%= j render partial: "admin/orders/show"%>');
$('#detail_<%= dom_id @order, :modal%>').modal('toggle');

app/views/admin/orders/update.js.erb
$("#order-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");
$(".edit_row_<%=@order.id%>").find('td:nth-child(3)').text("<%=order_status_converter(@order.status)%>").next().text("<%=time_ago(@order.created_at)%>").next().text("<%=time_ago(@order.updated_at)%>")