config/routes.rb
Rails.application.routes.draw do

    root 'home#index'

    devise_for :users, controllers: {
      sessions: 'users/sessions',
      registrations: "users/registrations"
    }

    # devise_for :admins, :controllers => { :registrations => :registrations }
    devise_for :admins, :skip => [:registrations]

    devise_scope :admin do
      get "/signin" => "devise/sessions#new", :as => "signin" # custom path to login/sign_in
    end

    devise_scope :user do
      get "/sign_in" => "devise/sessions#new", :as => "sign_in" # custom path to login/sign_in
      get "/sign_up" => "devise/registrations#new", :as => "sign_up" # custom path to login/sign_in
      get "users/verify/" => 'users/registrations#show_verify', as: 'verify'
      post "users/verify"
      post "users/resend"
    end

    as :admin do
      get 'admins/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
      put 'admins' => 'devise/registrations#update', :as => 'admin_registration'
      patch 'admins' => 'devise/registrations#update', :as => 'update_admin_registration'
    end


    namespace :admin do
      root "dashboards#index"
      get 'dashboards' => "dashboards#index", :as => "dashboard"
      resources :portfolios
      resources :categories
      resources :blogs
      resources :admins
      # Sale
      resources :category_portfolios
      resources :products
      resources :product_types
      resources :galleries
      resources :orders
      resources :line_items
      resources :settings, only: [:new, :create, :edit, :update]
      resources :users
      resources :settings, only: [:new, :create, :edit, :update]
      resources :incomes
      resources :expenses
      resources :accounts
      resources :income_and_expense_dashboards
    end

    resources :blogs

    resources :wishlists
    resources :products do
      resources :reviews
    end

    resources :orders
    resources :product_types, only: [:index, :show]
    get 'profiles' => "orders#profile", :as => "profiles"
    get 'carts/:id' => 'carts#show', as: "cart"
    delete 'carts/:id' => 'carts#destroy'

    post 'line_items/:id/add' => 'line_items#add_quantity', as: 'line_item_add'
    post 'line_items/:id/reduce' => 'line_items#reduce_quantity', as: 'line_item_reduce'
    post 'line_items/:id/s_size'=> 'line_items#s_size', as: 's_size'
    post 'line_items/:id/m_size'=> 'line_items#m_size', as: 'm_size'
    post 'line_items/:id/l_size'=> 'line_items#l_size', as: 'l_size'
    post 'line_items/:id/xl_size'=> 'line_items#xl_size', as: 'xl_size'
    post 'line_items' => 'line_items#create'
    get 'line_items/:id' => 'line_items#shiow', as: "line_item"
    delete 'line_items/:id' => 'line_items#destroy'

    post 'wishlist_line_items/:id/add' => 'wishlist_line_items#add_quantity', as: 'wishlist_line_item_add'
    post 'wishlist_line_items/:id/reduce' => 'wishlist_line_items#reduce_quantity', as: 'wishlist_line_item_reduce'
    post 'wishlist_line_items' => 'wishlist_line_items#create'
    get 'wishlist_line_items/:id' => 'wishlist_line_items#shiow', as: "wishlist_line_item"
    delete 'wishlist_line_items/:id' => 'wishlist_line_items#destroy'

    get 'users' => 'users#index', :as => "users"
    post 'users' => "users#create"
    get 'signup' => "users#new", :as => "new_user"
    get "users/:id/edit" => "users#edit", :as => "edit_user"
    get "users/:id" => "users#show", :as => "user"
    patch "users/:id" => "users#update"
    put "users/:id" => "users#update"
    delete "users/:id" => "users#destroy"

    get 'under_constructions' => "static_pages#under_construction", as: "under_construction"
    get 'profile' => "orders#profile", as: "profile"
    resources :product_types
end

app/models/income.rb
class Income < ApplicationRecord
  belongs_to :admin
  belongs_to :account, optional: true
  has_many :account_details

  def total_income
    sum = 0
    Income.all.each do |income|
      sum += income.amount
    end
    sum
  end

  def total_income_plus_account
    sum = 0
    Account.all.each do |account|
      sum += account.amount
      account.incomes.each do |income|
        sum = sum + income.amount
      end
    end
    sum
  end

  SELECT_CATEGORY = [
    "Work",
    "Teach"
  ]
end

app/controllers/admin/incomes_controller.rb
class Admin::IncomesController < ApplicationController

  before_action :authenticate_admin!
  before_action :admin_only?

  def index
    @income= current_admin.incomes.build
    @incomes = Income.all

  end

  def show
    @incomes= Income.find(params[:id])
  end

  def new

  end

  def create
    @income= current_admin.incomes.build(income_params)
    if @income.save
      @account = @income.account
      AccountDetail.create!(
        income_id: @income.id,
        account_id: @account.id,
        total: @income.amount + Account.sum(:amount)
      )
      respond_to do |format|
        flash.now[:notice] = "Successful Created"
        format.html { redirect_to admin_incomes_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or incomesDuplicated"
        format.html { redirect_to admin_incomes_path }
        format.js { render template: "admin/incomes/income_error.js.erb" }
      end
    end
  end

  def edit
    @income= Income.find(params[:id])
  end

  def update
    @income= Income.find(params[:id])
    if @income.update(income_params)
      respond_to do |format|
        flash.now[:notice] = "Successful Updated"
        format.html { redirect_to admin_incomes_path }
        format.js
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please fill the field blank or Duplicated"
        format.html { redirect_to admin_incomes_path }
        format.js { render template: "admin/incomes/income_error.js.erb" }
      end
    end
  end

  def destroy
    @income= Income.destroy(params[:id])
    respond_to do |format|
      flash.now[:error] = "Delete"
      format.html { redirect_to admin_incomes_url }
      format.js
    end
  end

  private
    def admin_only?
      unless  current_admin.admin?
        unless @user == current_admin
          redirect_to admin_dashboard_path, alert: "Access Denied"
        end
      end
    end


    def income_params
      params.required(:income).permit!
    end


end

app/views/admin/incomes/_edit.html.erb
<%=content_tag :div, class: "modal fade modal-slide-right", id: "edit_#{dom_id(@income, :modal)}" do%>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <div class="row">
          <div class="col-md-12">
            <h5 class="m-b-0" id="edit_user">Edit Income</h5>
          </div>
        </div>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%=simple_form_for([:admin, @income], remote: true) do |f|%>
        <div class="modal-body overflow-auto">
          <div class="form-row">
            <div class="form-group col-md-6">
              <label>Account</label>
              <%= f.collection_select :account_id, Account.all, :id, :account_name, {}, {:class=>"form-control"} %>
            </div>
            <div class="form-group col-md-6">
              <label>Category</label>
              <%= f.select :category, Income::SELECT_CATEGORY, {}, {:class=>"form-control"} %>
            </div>
            <div class="form-group col-md-12">
              <label>Amount</label>
              <%=f.number_field :amount, class: "form-control"%>
            </div>
            <div class="form-group col-md-12">
              <label>Income Date</label>
              <%=f.date_field :income_date, class: "form-control"%>
            </div>
          </div>
        </div>
        <div class="modal-footer justify-content-start">
          <%=f.submit "Update", class: "btn btn-primary"%>
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        </div>
      <%end%>
    </div>
  </div>
<%end%>

app/views/admin/incomes/_income.html.erb
<div class="col-lg-4">
  <!--widget card begin-->
  <div class="card m-b-30">
    <div class="card-header">
      <div class="card-title">
        <i class="fa fa-btc" style="color: #4c66fb;"></i>
        Income Statement
      </div>
      <div class="card-controls">
        <div class="dropdown">
          <a href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fa fa-angle-down"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-left">
            <button class="dropdown-item" type="button">Transfer</button>
            <button class="dropdown-item" type="button">Adjustment</button>
            <%=link_to edit_admin_income_path(income),id: "link_#{income.id}",class: "dropdown-item", remote: true do %>
              Edit
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <h4 class="m-t-20 m-b-20" style="font-size: 24px;" id="edit_income_name_<%=income.id%>">
         <i class="fa fa-circle" style="color: green;"></i>
        <%=income.category%>
      </h4>
      <h4 class="m-t-20 m-b-20" style="font-size: 24px;" id="edit_income_amount_<%=income.id%>">
        <%=number_to_currency(income.amount)%>
      </h4>
      <div class="text-left p-b-20">
        <%=link_to admin_income_path(income), remote: true,class: "btn btn-primary", "data-target" => "bd-example-modal-lg-panhara" do %>
          View Detail
        <%end%>
      </div>
    </div>
  </div>
  <!-- Modal -->
</div>

app/views/admin/incomes/_income_form.html.erb
  <%=simple_form_for([:admin, @income], remote: true) do |f|%>
    <div class="form-row">
      <div class="form-group col-md-6">
        <label>Account</label>
        <%= f.collection_select :account_id, Account.all, :id, :account_name, {}, {:class=>"form-control"} %>
      </div>
      <div class="form-group col-md-6">
        <label>Category</label>
        <%= f.select :category, Income::SELECT_CATEGORY, {}, {:class=>"form-control"} %>
      </div>
      <div class="form-group col-md-12">
        <label>Amount</label>
        <%=f.number_field :amount, class: "form-control"%>
      </div>
      <div class="form-group col-md-12">
        <%=f.submit "Save User", class: "btn btn-primary"%>
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
   </div>
<%end%>

app/views/admin/incomes/_show.html.erb
<%=content_tag :div, class: "modal fade bd-example-modal-lg", id: "detail_#{dom_id(@income, :modal)}" do%>
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myLargeModalLabel">Large Modal</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <h3>I'm large modal</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit.
          Aspernatur, assumenda aut eaque eius error, eum expedita iusto nobis
          obcaecati, perspiciatis quae quos saepe similique! Iure non
          perspiciatis qui veniam vitae!
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">
          Close
        </button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
<%end%>

app/views/admin/incomes/create.js.erb
$("input#income_amount").val("");
$(".disabled").attr("disabled", false)
$("#income-errors").html(" ");
$("#income-success").html("<%= custom_flash_message%>");
$("#income-index").append("<%=escape_javascript render(@income)%>");
$("#total_income").html("<%=number_to_currency(@income.total_income)%>")
$("#total_income_plus_account").html("<%=number_to_currency(@income.total_income_plus_account)%>")
$(function() {
  $('.delete_income_<%=@income.id%>').submitOnCheck();
});

$('.delete_income_<%=@income.id%>').submitOnCheck();

app/views/admin/incomes/destroy.js.erb
$('.delete_income_<%=@income.id%>').remove();

app/views/admin/incomes/edit.js.erb
$('body').append('<%= j render partial: "admin/incomes/edit"%>');
$('#edit_<%= dom_id @income, :modal%>').modal('toggle');

app/views/admin/incomes/income_error.js.erb
$("input#income_amount").val("");
$("#income-errors").html("<br><%= j render partial: 'layouts/flash_errors', locals: {flash: :flash}%>");

app/views/admin/incomes/income_success.js.erb
$("input#income_amount").val("");
$("#income-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");

app/views/admin/incomes/index.html.erb
<%=render "admin/shared/aside"%>
<main class="admin-main">
  <!--site header begins-->
  <%=render "admin/shared/header"%>
  <!--site header ends -->
  <section class="admin-content">
    <div class="container">
      <div class="row m-t-30">
        <div class="col-md-12 col">
          <div class="kanban-item" style="margin-bottom: 0px;">
            <a class="kanban-item-title btn btn-primary" style="color: #fff;">
              <i class="mdi mdi-plus-circle-outline"></i>
              Add Income
            </a>
          </div>
        </div>
        <div class="col-lg-12  m-t-30">
          <!--widget card begin-->
          <div class="card m-b-30">
            <div class="card-body">
              <div class="row">
                <div class="col my-auto">
                  <div class="h6 text-muted ">Total Income
                  </div>
                </div>
                <div class="col-auto my-auto">
                  <div class="avatar">
                    <div class="avatar-title rounded-circle badge-soft-danger">
                      <i class="mdi mdi-heart  "></i>
                    </div>
                  </div>
                </div>
              </div>
              <h1 class="display-4 fw-600" id="total_income"><%=number_to_currency(@income.total_income)%></h1>
              <div class="h6">
                <span class="text-success">
                  <i class="mdi mdi-arrow-top-right"></i>
                  +0.65%
                </span>
                More activity than usual.
              </div>
            </div>
          </div>
          <!--widget card ends-->
        </div>
      </div>
      <!-- Content -->
        <div class="row m-t-30" id="income-index">
          <% if @incomes.any? %>
            <%= render @incomes%>
          <% end %>
        </div>
    </main>
    <div class="modal fade modal-slide-right" id="kanbanItemModal" tabindex="-1" role="dialog" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <div class="row">
              <div class="col-md-12">
                <h5 class="m-b-0">Create Icome</h5>
              </div>
            </div>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body overflow-auto">
            <div id="incomes">
              <div id="income-errors"></div>
              <div id="income-success"></div>
              <%=render partial: "income_form", locals: {income: @income}%>
            </div>
          </div>
        </div>
      </div>
    </div>

app/views/admin/incomes/show.js.erb
$('body').append('<%= j render partial: "admin/incomes/show"%>');
$('#detail_<%= dom_id @income, :modal%>').modal('toggle');

app/views/admin/incomes/update.js.erb
$("#income-success").html("<br><%= j render partial: 'layouts/flash_success', locals: {flash: :flash}%>");
$("#edit_income_name_<%=@income.id%>").html("<i class='fa fa-circle' style='color: green;''></i> <%=@income.category%>");
$("#edit_income_amount_<%=@income.id%>").html("<%=number_to_currency(@income.amount)%>");
$("#total_income").html("<%=number_to_currency(@income.total_income)%>");
$("#total_income_plus_account").html("<%=number_to_currency(@income.total_income_plus_account)%>")